import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  ArrowRight,
  Building2,
  ShieldCheck,
  Tags,
  FileWarning,
  BadgeCheck,
  ScrollText,
  Scale,
  DoorOpen,
  Link2,
  Eye,
  Repeat,
  Gauge,
} from 'lucide-react';

const problems = [
  {
    icon: Tags,
    lead: 'Prices with undisclosed markups.',
    body: 'A cask passed through two or three intermediaries before reaching the buyer, each adding a margin nobody disclosed. The buyer had no way to see the price the distillery actually sold at.',
  },
  {
    icon: FileWarning,
    lead: 'Ownership you couldn\u2019t independently verify.',
    body: 'Buyers holding a certificate from the seller, and nothing from the warehouse actually storing the cask. A certificate from the party who sold it to you is not title.',
  },
  {
    icon: ScrollText,
    lead: 'No delivery order.',
    body: 'The single document proving the warehouse recognises you as the owner \u2014 frequently never issued, and often never asked for, because buyers didn\u2019t know to ask.',
  },
  {
    icon: Gauge,
    lead: 'Valuations produced by the party doing the selling.',
    body: 'Projected growth curves and \u201Ccurrent market value\u201D figures generated by the same business that profits from the sale, with no independent comparable behind them.',
  },
  {
    icon: DoorOpen,
    lead: 'No realistic way out.',
    body: 'Buyers discovering that the exit they\u2019d been promised meant going back to the same broker, on the broker\u2019s terms, at the broker\u2019s price \u2014 if the broker was still trading at all.',
  },
];

const principles = [
  {
    icon: BadgeCheck,
    lead: 'Verified at source.',
    body: 'Every cask originates from the distillery that made it or an owner whose title we\u2019ve checked.',
  },
  {
    icon: Link2,
    lead: 'Provenance you can audit.',
    body: 'The ownership record is on-chain and independent of us.',
  },
  {
    icon: Eye,
    lead: 'Priced in the open.',
    body: 'The asking price and the fees are visible before you buy.',
  },
  {
    icon: Repeat,
    lead: 'A real way out.',
    body: 'Resale runs through the same open marketplace, not back through a broker.',
  },
  {
    icon: Scale,
    lead: 'We don\u2019t value your cask for you.',
    body: 'We show what casks actually sold for. We don\u2019t publish projected returns.',
  },
];

const About = () => {
  return (
    <div className="bg-background">
      {/* ============== HERO ============== */}
      <section className="relative overflow-hidden border-b border-border/40">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-transparent" />
        <div className="relative container mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24 lg:py-32">
          <div className="max-w-3xl animate-fade-in">
            <Badge variant="outline" className="mb-6 border-primary/40 text-primary bg-primary/5">
              Our story
            </Badge>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold font-playfair leading-[1.08] mb-6 heritage-text-gradient">
              We came to casks from the tanker trade.
            </h1>
            <p className="text-lg sm:text-xl text-muted-foreground leading-relaxed">
              ARIGI exists because we already knew what a properly documented spirits transaction looks
              like &mdash; and the cask market wasn&rsquo;t one.
            </p>
          </div>
        </div>
      </section>

      {/* ============== SECTION 1 ============== */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        <div className="max-w-3xl">
          <h2 className="text-3xl sm:text-4xl font-bold font-playfair mb-6 sm:mb-8">
            Where we came from
          </h2>
          <div className="space-y-5 text-base sm:text-lg text-muted-foreground leading-relaxed">
            <p>
              We didn&rsquo;t start in cask investment. We started in bulk spirits &mdash; buying and
              selling alcohol by the ISO tank and the IBC, moving product between distilleries, bonded
              warehouses and bottlers across Europe.
            </p>
            <p>
              That trade runs on paper you can check. Nothing moves without it. Who legally owns the
              liquid. Which bonded warehouse is holding it and under whose account. What the
              specification actually says. What comparable volume genuinely cleared at last month, not
              what someone claims it did. Ownership changes hands through documents that a warehouse, a
              customs authority and a bank all independently recognise.
            </p>
            <p className="text-foreground">
              It isn&rsquo;t glamorous. It&rsquo;s just verifiable. When you trade at volume, verifiable
              is the only thing that matters.
            </p>
          </div>
        </div>
      </section>

      {/* ============== SECTION 2 ============== */}
      <section className="border-y border-border/40 bg-card/30">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <div className="max-w-3xl">
            <h2 className="text-3xl sm:text-4xl font-bold font-playfair mb-6 sm:mb-8">
              Then we looked at how casks were being sold
            </h2>
            <div className="space-y-5 text-base sm:text-lg text-muted-foreground leading-relaxed">
              <p>
                A private buyer wanting a single cask of maturing whisky was walking into a different
                market entirely &mdash; and one with far less protection than the professional trade we
                came from.
              </p>
              <p>
                These are the practices we kept running into. We&rsquo;re describing patterns
                we&rsquo;ve seen across the sector, not any single company:
              </p>
            </div>
          </div>

          <ul className="mt-10 grid gap-4 sm:gap-5 max-w-4xl">
            {problems.map((p) => (
              <li key={p.lead}>
                <Card className="heritage-card border-border/50">
                  <CardContent className="p-5 sm:p-6 flex gap-4">
                    <span className="shrink-0 h-10 w-10 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
                      <p.icon className="h-5 w-5 text-primary" />
                    </span>
                    <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
                      <strong className="text-foreground font-semibold">{p.lead}</strong>{' '}
                      {p.body}
                    </p>
                  </CardContent>
                </Card>
              </li>
            ))}
          </ul>

          <p className="mt-10 max-w-3xl text-base sm:text-lg text-muted-foreground leading-relaxed">
            None of this requires anyone to be a criminal. Most of it is just an opaque market with
            misaligned incentives and no obligation to show its workings. But the effect on the buyer is
            the same: you cannot check what you own, what you paid, or what it&rsquo;s worth.
          </p>
        </div>
      </section>

      {/* ============== SECTION 3 ============== */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        <div className="max-w-3xl">
          <h2 className="text-3xl sm:text-4xl font-bold font-playfair mb-6">
            What we built instead
          </h2>
          <p className="text-base sm:text-lg text-muted-foreground leading-relaxed">
            ARIGI has two doors in, and only two.
          </p>
        </div>

        <div className="mt-10 grid gap-6 md:grid-cols-2 max-w-4xl">
          <Card className="heritage-card border-border/50 hover:border-primary/40 transition-all">
            <CardContent className="p-6 sm:p-8">
              <span className="h-12 w-12 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center mb-5">
                <Building2 className="h-6 w-6 text-primary" />
              </span>
              <h3 className="font-playfair font-semibold text-xl sm:text-2xl mb-3">
                Direct from the distillery
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                Casks listed by the distillery that filled them, at the distillery&rsquo;s own price. No
                chain of intermediaries between the still and you.
              </p>
            </CardContent>
          </Card>

          <Card className="heritage-card border-border/50 hover:border-primary/40 transition-all">
            <CardContent className="p-6 sm:p-8">
              <span className="h-12 w-12 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center mb-5">
                <ShieldCheck className="h-6 w-6 text-primary" />
              </span>
              <h3 className="font-playfair font-semibold text-xl sm:text-2xl mb-3">
                From a verified owner
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                Casks resold by someone who demonstrably owns them &mdash; ownership confirmed against
                our records and the warehouse&rsquo;s before a listing goes live, not asserted in a PDF.
              </p>
            </CardContent>
          </Card>
        </div>

        <p className="mt-10 max-w-3xl text-base sm:text-lg text-muted-foreground leading-relaxed">
          Every cask carries its provenance on-chain, so the record of who owned it and when isn&rsquo;t
          something we can quietly revise. It sits in a bonded warehouse, not in a spreadsheet. Fees are
          shown before you commit, not discovered afterwards. And because the same marketplace handles
          resale, the exit is the same transparent venue as the entry.
        </p>
      </section>

      {/* ============== SECTION 4 ============== */}
      <section className="border-y border-border/40 bg-card/30">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <h2 className="text-3xl sm:text-4xl font-bold font-playfair mb-10 max-w-3xl">
            What we hold ourselves to
          </h2>
          <ul className="grid gap-4 sm:gap-5 md:grid-cols-2 max-w-5xl">
            {principles.map((p) => (
              <li key={p.lead} className="flex gap-4">
                <span className="shrink-0 h-10 w-10 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
                  <p.icon className="h-5 w-5 text-primary" />
                </span>
                <p className="text-sm sm:text-base text-muted-foreground leading-relaxed pt-1.5">
                  <strong className="text-foreground font-semibold">{p.lead}</strong> {p.body}
                </p>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ============== CLOSING CTA ============== */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        <Card className="heritage-card border-primary/30 overflow-hidden">
          <CardContent className="p-8 sm:p-12 lg:p-16 text-center">
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold font-playfair mb-5 heritage-text-gradient">
              See what that looks like in practice.
            </h2>
            <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Every cask on ARIGI shows its distillery, its warehouse, its age and its full ownership
              history &mdash; before you spend anything.
            </p>
            <div className="mt-8 flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center">
              <Button asChild size="lg" className="heritage-button text-base px-8 h-12 group">
                <Link to="/marketplace">
                  Browse the marketplace
                  <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                </Link>
              </Button>
              <Button
                asChild
                size="lg"
                variant="outline"
                className="text-base px-8 h-12 border-primary/40 hover:bg-primary/10"
              >
                <Link to="/consumer-journey">How buying works</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </section>
    </div>
  );
};

export default About;
