// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnmmjmxhtbplfkdughxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZubW1qbXhodGJwbGZrZHVnaHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDEzNDksImV4cCI6MjA2OTI3NzM0OX0.WbuDozpDeJnKi1-F_N1YqyTeTKTO61LTsP4-lLaT-pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});